language: ruby

rvm:
  - 1.9.3
  - 2.4.3
  - 2.5.0
  - ruby-head

env:
  - DB=sqlite3
  - DB=mysql
  - DB=postgresql

gemfile:
  - gemfiles/rails_3_2.gemfile
  - gemfiles/rails_4_0.gemfile
  - gemfiles/rails_4_1.gemfile
  - gemfiles/rails_5_1.gemfile
  - gemfiles/rails_5_2.gemfile

#cache: bundler
before_install: gem install bundler
install: bundle install
script: bundle exec rake

matrix:
  fast_finish: true

  exclude:
    - rvm: 1.9.3
      gemfile: gemfiles/rails_4-0.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/rails_4-1.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/rails_3_2.gemfile
